
build:
# php images build
	docker build -t befeni/basic-server:1-production --target basic-server-production ./
	docker build -t befeni/basic-server:1-development --target basic-server-development ./
